version: '2'
services:
  airplay:
    build: ./airplay
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - snapcast:/var/cache/snapcast
  volumes:
  spotifycache:
  bluetoothcache:
  snapcast:
